version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypass
    ports:
      - "27017:27017"
    volumes:
      - my_mongo_data:/data/db

  app:
    image: nsoutage:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  
volumes:
  my_mongo_data:
