version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: outages


  app:
    image: nsoutage:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  
volumes:
  my_mongo_data:
