version: '3.8'

services:
  api:
    image: hermanyiqunliang/nsoutageapi:latest
    ports:
      - "8080:8080"
    environment:
      DISCORD_BOT_TOKEN : "Your Discord Bot Token"
      MONGO_URI : "Your MongoDB URI"
  app:
    image: hermanyiqunliang/nsoutagedc:latest
    ports:
      - "8081:8081"
    environment:
      DISCORD_BOT_TOKEN : "Your Discord Bot Token"
      MONGO_URI : "Your MongoDB URI"
  notify:
    image: hermanyiqunliang/nsoutagenotification:latest
    environment:
      DISCORD_BOT_TOKEN : "Your Discord Bot Token"
      MONGO_URI : "Your MongoDB URI"
