version: '3.8'

services:
  api:
    image: hermanyiqunliang/nsoutageapi:latest
    ports:
      - "8080:8080"

  app:
    image: hermanyiqunliang/nsoutagedc:latest
    ports:
      - "8081:8081"

  notify:
    image: hermanyiqunliang/nsoutagenotification:latest
    environment:
      API_URL: "api"
      APP_URL: "http://app:8081"
    depends_on:
      - api
      - app
