name: Deploy to Server via SSH

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: 45.76.139.194
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Stopping and removing all Docker containers..."
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            echo "Removing all Docker images..."
            docker rmi -f $(docker images -q)
            echo "Removing all Docker volumes..."
            docker volume rm $(docker volume ls -q)
            echo "Removing all Docker networks (except default ones)..."
            docker network ls | grep -v "bridge\|none\|host" | awk '{print \$1}' | xargs docker network rm
            cd /root
            docker-compose up -d --build
