name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Clean up and Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@45.76.139.194 << 'EOF'
            echo "Stopping and removing all Docker containers..."
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            echo "Removing all Docker images..."
            docker rmi -f $(docker images -q)
            echo "Removing all Docker volumes..."
            docker volume rm $(docker volume ls -q)
            echo "Removing all Docker networks (except default ones)..."
            docker network ls | grep "bridge\|none\|host" | awk '{print \$1}' | xargs docker network rm
            cd /path/to/your/project
            docker-compose up -d --build
          EOF
